image_width: 1440
image_height: 1080
camera_name: narrow_stereo_second
camera_matrix:
  rows: 3
  cols: 3
  data: [1766.67542,    0.     ,  681.95133,
            0.     , 1764.1012 ,  576.05591,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.065987, 0.098867, -0.002842, -0.001483, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1750.81982,    0.     ,  679.71686,    0.     ,
            0.     , 1753.47705,  574.39064,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
