image_width: 1440
image_height: 1080
camera_name: narrow_stereo_first
camera_matrix:
  rows: 3
  cols: 3
  data: [1766.16564,    0.     ,  759.67858,
            0.     , 1763.81837,  575.65057,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.068906, 0.070917, 0.000342, -0.000472, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1747.90283,    0.     ,  759.33674,    0.     ,
            0.     , 1751.59937,  575.66903,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]