image_width: 1440
image_height: 1080
camera_name: narrow_stereo_first
camera_matrix:
  rows: 3
  cols: 3
  data: [2586.14505,    0.     ,  768.29086,
            0.     , 2578.45473,  508.69845,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.162323, 0.043988, -0.002284, 0.001136, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2550.70996,    0.     ,  769.70973,    0.     ,
            0.     , 2556.77466,  506.98179,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
